version: '3'

services:
  traefik:
      image: traefik
      restart:
        always
      command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
      ports:
        - 80:80
        - 8080:8080
        - 443:443
      networks:
        - webgateway
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /dev/null:/traefik.toml
      cap_drop:
        - all
      cap_add:
        - net_bind_service

networks:
  webgateway:
    driver: bridge
