version: "3"

networks:
  sharednetwork:
    external: true

services:
  traefik:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: traefik-common
    labels:
      - "traefik.port=8080"
      - "traefik.docker.network=sharednetwork"
    networks:
      - sharednetwork
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    restart:
      always
    volumes:
      - ./docker/config/traefik.toml:/etc/traefik/traefik.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # Enable logs if need
    # - ./config/logs/:/etc/traefik/logs/
